# Generated by Django 4.2.5 on 2023-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='image',
            field=models.ImageField(upload_to='media/about'),
        ),
    ]
