# Generated by Django 4.2.5 on 2023-09-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_aboutproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='color',
            field=models.CharField(choices=[('жёлтый', '#fdba2c'), ('красный', '#d22115'), ('зелёный', '#9acd32'), ('фуксия', '#a630a2'), ('чёрный', '#1d1d1b')], default='жёлтый', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='image',
            field=models.ImageField(upload_to='about'),
        ),
    ]
