# Generated by Django 4.2.5 on 2023-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_aboutproject_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutproject',
            name='color',
            field=models.CharField(choices=[('#fdba2c', 'жёлтый'), ('#d22115', 'красный'), ('#9acd32', 'зелёный'), ('#a630a2', 'фуксия'), ('#1d1d1b', 'чёрный')], default='#fdba2c', max_length=100),
        ),
    ]
