version: '3.8'

services:
  react:
    container_name: client
    build:
      context: ./client
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_PORT=${VITE_API_PORT}
      - VITE_SSL=${VITE_SSL}
    ports:
      - "3000:3000"
    depends_on:
      - django

  django:
    container_name: server
    build:
      context: ./server
    env_file:
      - ".env"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=database 
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    ports:
      - "5001:8000"
    volumes:
      - ./server/media:/server/media
      - ./server/static:/server/static
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

volumes:
  data:
  media:
  static:
